import { QuadrantInfo } from '../types';

export const QUADRANT_CONFIG: QuadrantInfo[] = [
  {
    id: 'Q1',
    title: 'Urgente & Importante',
    subtitle: 'Urgente + Importante',
    action: 'FAÇA AGORA',
    emoji: '🔴',
    description: 'Crises, prazos críticos, emergências',
    urgency: true,
    importance: true,
    colors: {
      bg: 'bg-white',
      border: 'border-red-200',
      header: 'from-red-600 to-rose-500',
      badge: 'bg-red-500',
      button: 'bg-red-600 hover:bg-red-500',
      text: 'text-red-600',
      glow: 'shadow-red-100',
      ring: 'ring-red-300/50',
      cardBg: 'bg-red-50',
      cardBorder: 'border-red-200',
      cardBar: 'bg-red-500',
      cardTitle: 'text-red-900',
    },
  },
  {
    id: 'Q2',
    title: 'Importante, Não Urgente',
    subtitle: 'Importante + Não Urgente',
    action: 'PLANEJE',
    emoji: '🔵',
    description: 'Crescimento, planejamento, desenvolvimento',
    urgency: false,
    importance: true,
    colors: {
      bg: 'bg-white',
      border: 'border-blue-200',
      header: 'from-blue-600 to-indigo-500',
      badge: 'bg-blue-500',
      button: 'bg-blue-600 hover:bg-blue-500',
      text: 'text-blue-600',
      glow: 'shadow-blue-100',
      ring: 'ring-blue-300/50',
      cardBg: 'bg-blue-50',
      cardBorder: 'border-blue-200',
      cardBar: 'bg-blue-400',
      cardTitle: 'text-blue-900',
    },
  },
  {
    id: 'Q3',
    title: 'Urgente, Não Importante',
    subtitle: 'Urgente + Não Importante',
    action: 'DELEGUE',
    emoji: '🟡',
    description: 'Interrupções, reuniões desnecessárias',
    urgency: true,
    importance: false,
    colors: {
      bg: 'bg-white',
      border: 'border-amber-200',
      header: 'from-amber-600 to-orange-500',
      badge: 'bg-amber-500',
      button: 'bg-amber-600 hover:bg-amber-500',
      text: 'text-amber-600',
      glow: 'shadow-amber-100',
      ring: 'ring-amber-300/50',
      cardBg: 'bg-amber-50',
      cardBorder: 'border-amber-200',
      cardBar: 'bg-amber-300',
      cardTitle: 'text-amber-900',
    },
  },
  {
    id: 'Q4',
    title: 'Não Urgente, Não Importante',
    subtitle: 'Não Urgente + Não Importante',
    action: 'ELIMINE',
    emoji: '⚫',
    description: 'Distrações, redes sociais, desperdício de tempo',
    urgency: false,
    importance: false,
    colors: {
      bg: 'bg-white',
      border: 'border-slate-200',
      header: 'from-slate-500 to-slate-400',
      badge: 'bg-slate-400',
      button: 'bg-slate-500 hover:bg-slate-400',
      text: 'text-slate-500',
      glow: 'shadow-slate-100',
      ring: 'ring-slate-300/50',
      cardBg: 'bg-white',
      cardBorder: 'border-slate-200',
      cardBar: 'bg-slate-300',
      cardTitle: 'text-slate-600',
    },
  },
];

export const MOTIVATIONAL_QUOTES = [
  'O que é importante raramente é urgente, e o que é urgente raramente é importante. — Eisenhower',
  'Disciplina é a ponte entre objetivos e realizações.',
  'Foque no que importa, ignore o que distrai.',
  'Cada tarefa concluída é um passo em direção aos seus objetivos.',
  'O tempo é o recurso mais precioso que possuímos.',
  'Produtividade não é fazer mais, é fazer o que importa.',
];
